REM *************
REM
REM EL DILEMA DEL PRISIONERO
REM
REM *************
REM
LET Q=0
LET G=0
LET T=1
LET P=(G/T+(10-G)/(20-T))/2
IF Q>P THEN 50
LET Q=P 
LET F=G
LET S=T 
LET T=T+1
IF T>=11 THEN 80
GOTO 20
LET G=G+1
IF G>=11 THEN 110
LET T=G
GOTO 20
PRINT "LA PROBABILIDAD MAXIMA ES" ;Q
PRINT
PRINT "EL PRISIONERO DEBERIA COLOCAR" ;F
PRINT "CANICAS VERDES" ;
PRINT "Y" ;S-F; "CANICAS ROJAS EN LA PRIMERA URNA CON OBJETO DE MAXIMIZAR LA PROBABLIDAD DE SER LIBRE."
END
