REM ********************
REM
REM EL JUEGO DEL 100
REM
REM ********************
REM
PRINT "DAME UN NUMERO DECIMAL ENTRE 0 Y 1"
INPUT R 
LET T=0
PRINT "+++++++++++++++++++++++++++++++++++++++++++++++":PRINT:PRINT
PRINT "LA SUMA TOTAL ES" ;T
PRINT
PRINT "CUANTO QUIERE SUMAR AL TOTAL?";
INPUT S
IF S<1 THEN 37
IF S<11 THEN 39
PRINT
PRINT "¡VALOR INVALIDADO! SUME UN ENTERO":PRINT"COMPRENDIDO ENTRE 1 Y 10."
PRINT:GOTO 32
LET T=T+S
PRINT:PRINT"ESTO HACE UN TOTAL DE";T:PRINT
IF T<100 THEN 47
PRINT "TU GANAS! QUIERES VOLVER A JUGAR?";
INPUT W$
IF W$="S" THEN 20
GOTO 100
LET S=11*INT((T+9)/11)-T+1
IF S <>O THEN 80
LET R1=(R+3.14159)↑5
LET R=R1-INT(R1)
LET S=INT(10*R)+1
PRINT "YO ELIJO PARA AÑADIR";S:PRINT
LET T=T+S
PRINT "-----------------------------------------------------------"
IF T<100 THEN 30
PRINT:PRINT:PRINT"*************************************************":PRINT:PRINT
PRINT "QUIERES VOLVER A JUGAR?";
INPUT W$
IF W$="S" THEN 20
END
