REM ***********************
REM
REM LA CADENA MAS LARGA
REM
REM ***********************
REM
LET N=100
LET B=0
LET N=N-1
LET M=N
LET I=1
IF N=0 THEN 140
IF M/2=INT(M/2) THEN 70
LET M=3*M+1
GOTO 80
LET M=M/2
LET I=I+1
IF M=4 THEN 110
GOTO 50
IF I<B THEN 130
LET A=N
LET B=I
GOTO 20
PRINT "EL ENTERO DE LA CADENA MAS LARGA ES";A
PRINT "LA LONGITUD DE LA CADENA ES";B
END
