REM ***********************
REM
REM LA CUERDA ANUDADA
REM
REM ***********************
REM
LET A=1
LET P=90
LET K=0
LET N=45-A
LET D=1-A/90
LET B=N/D
IF A>B THEN 95
IF B<>INT(B) THEN 80
LET C=90-A-B
LET K=K+1
PRINT 
PRINT "LOS LADOS SON";A;"";B;" Y ";C
LET A=A+1
GORO 20
PRINT
PRINT "EL NUMERO TOTAL DE TRIANGULOS POSIBLES"
PRINT "ES ";K
END
