REM ***********************
REM
REM LA FLOTA DE CAMIONES
REM
REM ***********************
REM
LET N=0
LET T=0
LET N=N+1
IF N>500 THEN 100
LET D=INT(LOG(N)/LOG(10))+1
IF N=1 THEN 70
LET P=INT(10↑D*(N*N/10↑D-INT(N*N/10↑D))+.5)
IF P<>N THEN 90
PRINT "CAMION NUMERO";N 
LET T=T+1
GOTO 20
PRINT:PRINT"EL NUMERO TOTAL DE CAMIONES EN LA FLOTA ES";T
END
