REM ***********************
REM
REM LA MAQUINA DE REDUCIR FRACCIONES
REM
REM ***********************
REM
PRINT "CUAL ES EL NUMERADOR?";
INPUT N
PRINT "CUAL ES EL DENOMINADOR?";
INPUT 
PRINT
LET E=M
LET F=N
LET G=INT(F/E)
LET H=F-G*E
IF H=0 THEN 90
LET F=E
LET E=H
GOTO 30
LET S=E
LET U=N/S
LET V=M/S
PRINT "LA FRACCION ";N; "/";M
PRINT
PRINT "SE REDUCE A";U; "/";V
END
