REM ***************
REM
REM LA PIRAMIDE DE BOLAS
REM
REM ***************
REM
LET K=1
LET T=0
LET T=T+K*K
IF T>10000 THEN 50
LET K=K+1
GOTO 20
LET T=T-K*K
LET K=K-1
LET U=10000-T
PRINT "EL NUMERO DE CAPAS ES" ;K
PRINT "EL NUMERO DE BOLAS UTILIZADAS ES" ;T
PRINT "EL NUMERO DE BOLAS NO UTILIZADAS ES " ;U
END
