REM ***********************
REM
REM NUMEROS PERFECTOS
REM
REM ***********************
REM
LET N=1
LET N=N+1
IF N>999 THEN 170
LET D=0:LET S=0
LET D=D+1
IF D>N/2 THEN 140
LET C=N/D
IF C=INT(C) THEN 100
GOTO 50
LET S=S+D
IF S>N THEN 130
GOTO 50
GOTO 20
IF N<>S THEN 160
PRINT "UN NUMERO PERFECTO ES EL ";N
GOTO 20
END
