REM ***********************
REM
REM SUCESIONES ARITMETICAS
REM
REM ***********************
REM
REM **********DATOS DE ENTRADA***************
HOME:REM LIMPIA LA PANTALLA
PRINT "SUCESIONES ARITMETICAS"
PRINT
PRINT "INTRODUZCA EL PRIMER TERMINO";
INPUT A 
PRINT
PRINT "INTRODUZCA LA RAZON";
INPUT D
PRINT
PRINT "NUMERO DE TERMINOS DE LA SUCESION"
INPUT N
REM
REM **********CALCULOS Y SALIDA DE RESULTADOS*******************
PRINT "LA SUCESION DE TERMINOS ES"
PRINT
LET TERM = A
LET SUM = 0
FOR I = 1 TO N
PRINT TERM;",";
LET SUM = SUM + TERM
LET TERM = TERM + D
NEXT I
PRINT "....."
PRINT
PRINT
PRINT "LA SUMA ES = ";SUM
PRINT
REM ***************CONTINUA?******************
PRINT "DESEA CONTINUAR? S/N"
INPUT G$: IF G$ <> "N" THEN 1110
END
